### ISSUE TITLE
I found a bug in this repository.

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [nimadez/voxel-builder#1]
When I import a file from the oldest version of the Voxel Builder, the .vox file is not showing up on the latest version. I am working on a blender project, and the newest version is not accepting the file. Why is it doing this?

**Comment by TheRealDigitalMaster** [comment]
Old version: ![Screenshot 2022-09-07 08 18 22](https://user-images.githubusercontent.com/112659665/188876675-abc81e6c-55ed-4b97-a588-3354778acad8.png)
New version:
![Screenshot 2022-09-07 08 18 39](https://user-images.githubusercontent.com/112659665/188876716-18981d25-5420-410d-aeae-5666194968b3.png)

**Comment by nimadez** [comment]
That's not a bug, but thank you for the report!
File format changed since v3.6.0, to add new layering system,
To fix that, just add "**,true**" to every single line. _(try VSCode to find and replace in batch)_

[ Old file format ]
0,0,0,#FFFFFF
1,1,1,#FFFFFF

[ New file format ]
0,0,0,#FFFFFF,true
1,1,1,#FFFFFF,false

**Comment by TheRealDigitalMaster** [comment]
Ok thanks! It will take a while, but I guess it is the only way lol

**Comment by TheRealDigitalMaster** [comment]
Ok thanks! This helps a lot :D

**Comment by nimadez** [comment]
New [File Format Updater](https://github.com/nimadez/voxel-builder/blob/main/addons/update-file-format.py) addon for backward compatibility
Thank you @TheRealDigitalMaster

**Comment by TheRealDigitalMaster** [comment]
YW :)
